In [20]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [56]:
df = pd.read_csv("movies_metadata.csv")

In [57]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [58]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [59]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(13)

In [26]:
df.drop_duplicates(inplace= True)

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [29]:
df = df[['title','genres','overview','tagline','popularity','vote_average']]

In [30]:
df

,title,genres,overview,tagline,popularity,vote_average
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",NaN,21.946943,7.7
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,6.9
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.7129,6.5
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,6.1
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,5.7
...,...,...,...,...,...,...
45461,Subdue,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman.,Rising and falling between a man and woman,0.072051,4.0
45462,Century of Birthing,"[{'id': 18, 'name': 'Drama'}]",An artist struggles to finish his work while a...,NaN,0.178241,9.0
45463,Betrayal,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","When one of her hits goes wrong, a professiona...",A deadly game of wits.,0.903007,3.8
45464,Satan Triumphant,[],"In a small town live two brothers, one a minis...",NaN,0.003503,0.0
45465,Queerama,[],50 years after decriminalisation of homosexual...,NaN,0.163015,0.0

In [31]:
df.isnull().sum()
df.shape

(45453, 6)

In [32]:
df['title'].dropna(inplace=True)

In [33]:
df['overview'].fillna(" ",inplace=True)
df['tagline'].fillna(" ",inplace=True)

In [34]:
df['popularity'].fillna(" ",inplace=True)
df['vote_average'].fillna(" ",inplace=True)

In [35]:
df.isnull().sum()

title           6
genres          0
overview        0
tagline         0
popularity      0
vote_average    0
dtype: int64

In [36]:
df.shape

(45453, 6)

In [37]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [38]:
import ast
df['genres']=df['genres'].apply(lambda x : " ".join([i['name'] for i in ast.literal_eval(x)]) )

In [39]:
df.head()

,title,genres,overview,tagline,popularity,vote_average
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,21.946943,7.7
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,6.9
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.7129,6.5
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,6.1
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,5.7

In [40]:
df['tag']=df['tagline']+df['title']+df['genres']+df['overview']

In [41]:
df

,title,genres,overview,tagline,popularity,vote_average,tag
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,21.946943,7.7,"Toy StoryAnimation Comedy FamilyLed by Woody,..."
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,6.9,Roll the dice and unleash the excitement!Juman...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.7129,6.5,Still Yelling. Still Fighting. Still Ready for...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,6.1,Friends are the people who let you be yourself...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,5.7,Just When His World Is Back To Normal... He's ...
...,...,...,...,...,...,...,...
45461,Subdue,Drama Family,Rising and falling between a man and woman.,Rising and falling between a man and woman,0.072051,4.0,Rising and falling between a man and womanSubd...
45462,Century of Birthing,Drama,An artist struggles to finish his work while a...,,0.178241,9.0,Century of BirthingDramaAn artist struggles t...
45463,Betrayal,Action Drama Thriller,"When one of her hits goes wrong, a professiona...",A deadly game of wits.,0.903007,3.8,A deadly game of wits.BetrayalAction Drama Thr...
45464,Satan Triumphant,,"In a small town live two brothers, one a minis...",,0.003503,0.0,Satan TriumphantIn a small town live two brot...
45465,Queerama,,50 years after decriminalisation of homosexual...,,0.163015,0.0,Queerama50 years after decriminalisation of h...

In [42]:
import nltk
from nltk.corpus import stopwords
import re
from nltk.stem import WordNetLemmatizer

In [43]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\parth\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\parth\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [44]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [45]:
def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #removed the punctuations
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)


     

df['tag'] = df['tag'].apply(preprocess_text)
     


     

df = df.reset_index(drop = True)
     

indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45448
Century of Birthing            45449
Betrayal                       45450
Satan Triumphant               45451
Queerama                       45452
Length: 45453, dtype: int64

In [46]:
df

,title,genres,overview,tagline,popularity,vote_average,tag
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,21.946943,7.7,toy storyanimation comedy familyled woody andy...
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,6.9,roll dice unleash excitementjumanjiadventure f...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.7129,6.5,still yelling still fighting still ready loveg...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,6.1,friend people let never let forget itwaiting e...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,5.7,world back normal he surprise lifefather bride...
...,...,...,...,...,...,...,...
45448,Subdue,Drama Family,Rising and falling between a man and woman.,Rising and falling between a man and woman,0.072051,4.0,rising falling man womansubduedrama familyrisi...
45449,Century of Birthing,Drama,An artist struggles to finish his work while a...,,0.178241,9.0,century birthingdramaan artist struggle finish...
45450,Betrayal,Action Drama Thriller,"When one of her hits goes wrong, a professiona...",A deadly game of wits.,0.903007,3.8,deadly game witsbetrayalaction drama thrillerw...
45451,Satan Triumphant,,"In a small town live two brothers, one a minis...",,0.003503,0.0,satan triumphantin small town live two brother...
45452,Queerama,,50 years after decriminalisation of homosexual...,,0.163015,0.0,queerama year decriminalisation homosexuality ...

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [48]:
tfidf = TfidfVectorizer(max_features = 50000,ngram_range=(1,2),stop_words = 'english')

In [49]:
tfidf_matrix= tfidf.fit_transform(df['tag'])

In [50]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1444453 stored elements and shape (45453, 50000)>

In [51]:
from sklearn.metrics.pairwise import cosine_similarity

In [52]:
def recommend(title , n=10):
    if title not in indices :
        return ['Movie not found']
    idx = indices[title]
    sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
    similar_idx = sim_score.argsort()[::-1][1:n+1]
    return df['title'].iloc[similar_idx]

In [53]:
recommend('Jumanji')

9500                         Word Wars
30238                  The Games Maker
19786            Indie Game: The Movie
14724    The Living Room of the Nation
15508                  Le Pont du Nord
37435               The Ouija Exorcism
30386                           Pixels
44459                      Open Graves
44363                Liar Game: Reborn
8800                           Quintet
Name: title, dtype: object

In [54]:
recommend('Avatar',3)

37998             Sharkman
3656     Project Moon Base
28945       20 Years After
Name: title, dtype: object

In [55]:
recommend("Toy Story")

2996                                     Toy Story 2
15344                                    Toy Story 3
24514                                      Small Fry
36718                                 Toy Reanimator
17184                                      Group Sex
25688    Silent Night, Deadly Night 5: The Toy Maker
24738                   How the Toys Saved Christmas
6434                          What's Up, Tiger Lily?
1931                                       Condorman
43235                        The Mouse and His Child
Name: title, dtype: object